import { CodeIcon } from '@sanity/icons'
import { defineField, defineType } from 'sanity'

export const codeFile = defineType({
    name: 'code-file',
    type: 'object',
    icon: CodeIcon,
    fields: [
        defineField({
            name: 'name',
            type: 'string',
            title: 'File Name',
            placeholder: 'e.g. "example.ts"',
            initialValue: '',
            validation: rule => [rule.required(), rule.max(120)],
        }),
        defineField({
            name: 'type',
            type: 'string',
            title: 'File Type',
            initialValue: 'rust',
            options: {
                list: [
                    { title: 'abap', value: 'abap' },
                    { title: 'actionscript-3', value: 'actionscript-3' },
                    { title: 'ada', value: 'ada' },
                    { title: 'adoc', value: 'adoc' },
                    { title: 'angular-html', value: 'angular-html' },
                    { title: 'angular-ts', value: 'angular-ts' },
                    { title: 'apache', value: 'apache' },
                    { title: 'apex', value: 'apex' },
                    { title: 'apl', value: 'apl' },
                    { title: 'applescript', value: 'applescript' },
                    { title: 'ara', value: 'ara' },
                    { title: 'asciidoc', value: 'asciidoc' },
                    { title: 'asm', value: 'asm' },
                    { title: 'astro', value: 'astro' },
                    { title: 'awk', value: 'awk' },
                    { title: 'ballerina', value: 'ballerina' },
                    { title: 'bash', value: 'bash' },
                    { title: 'bat', value: 'batQuote' },
                    { title: 'batch', value: 'batch' },
                    { title: 'be', value: 'be' },
                    { title: 'beancount', value: 'beancount' },
                    { title: 'berry', value: 'berry' },
                    { title: 'bibtex', value: 'bibtex' },
                    { title: 'bicep', value: 'bicep' },
                    { title: 'blade', value: 'blade' },
                    { title: 'bsl', value: 'bsl' },
                    { title: 'c', value: 'c' },
                    { title: 'c#', value: 'c#' },
                    { title: 'c++', value: 'c++' },
                    { title: 'cadence', value: 'cadence' },
                    { title: 'cairo', value: 'cairo' },
                    { title: 'cdc', value: 'cdc' },
                    { title: 'clarity', value: 'clarity' },
                    { title: 'clj', value: 'clj' },
                    { title: 'clojure', value: 'clojure' },
                    { title: 'closure-templates', value: 'closure-templates' },
                    { title: 'cmake', value: 'cmake' },
                    { title: 'cmd', value: 'cmd' },
                    { title: 'cobol', value: 'cobol' },
                    { title: 'codeowners', value: 'codeowners' },
                    { title: 'codeql', value: 'codeql' },
                    { title: 'coffee', value: 'coffee' },
                    { title: 'coffeescript', value: 'coffeescript' },
                    { title: 'common-lisp', value: 'common-lisp' },
                    { title: 'console', value: 'console' },
                    { title: 'coq', value: 'coq' },
                    { title: 'cpp', value: 'cpp' },
                    { title: 'cql', value: 'cql' },
                    { title: 'crystal', value: 'crystal' },
                    { title: 'cs', value: 'cs' },
                    { title: 'csharp', value: 'csharp' },
                    { title: 'css', value: 'css' },
                    { title: 'csv', value: 'csv' },
                    { title: 'cue', value: 'cue' },
                    { title: 'cypher', value: 'cypher' },
                    { title: 'd', value: 'd' },
                    { title: 'dart', value: 'dart' },
                    { title: 'dax', value: 'dax' },
                    { title: 'desktop', value: 'desktop' },
                    { title: 'diff', value: 'diff' },
                    { title: 'docker', value: 'docker' },
                    { title: 'dockerfile', value: 'dockerfile' },
                    { title: 'dotenv', value: 'dotenv' },
                    { title: 'dream-maker', value: 'dream-maker' },
                    { title: 'edge', value: 'edge' },
                    { title: 'elisp', value: 'elisp' },
                    { title: 'elixir', value: 'elixir' },
                    { title: 'elm', value: 'elm' },
                    { title: 'emacs-lisp', value: 'emacs-lisp' },
                    { title: 'erb', value: 'erb' },
                    { title: 'erl', value: 'erl' },
                    { title: 'erlang', value: 'erlang' },
                    { title: 'f', value: 'f' },
                    { title: 'f#', value: 'f#' },
                    { title: 'f03', value: 'f03' },
                    { title: 'f08', value: 'f08' },
                    { title: 'f18', value: 'f18' },
                    { title: 'f77', value: 'f77' },
                    { title: 'f90', value: 'f90' },
                    { title: 'f95', value: 'f95' },
                    { title: 'fennel', value: 'fennel' },
                    { title: 'fish', value: 'fish' },
                    { title: 'fluent', value: 'fluent' },
                    { title: 'for', value: 'for' },
                    { title: 'fortran-fixed-form', value: 'fortran-fixed-form' },
                    { title: 'fortran-free-form', value: 'fortran-free-form' },
                    { title: 'fs', value: 'fs' },
                    { title: 'fsharp', value: 'fsharp' },
                    { title: 'fsl', value: 'fsl' },
                    { title: 'ftl', value: 'ftl' },
                    { title: 'gdresource', value: 'gdresource' },
                    { title: 'gdscript', value: 'gdscript' },
                    { title: 'gdshader', value: 'gdshader' },
                    { title: 'genie', value: 'genie' },
                    { title: 'gherkin', value: 'gherkin' },
                    { title: 'git-commit', value: 'git-commit' },
                    { title: 'git-rebase', value: 'git-rebase' },
                    { title: 'gjs', value: 'gjs' },
                    { title: 'gleam', value: 'gleam' },
                    { title: 'glimmer-js', value: 'glimmer-js' },
                    { title: 'glimmer-ts', value: 'glimmer-ts' },
                    { title: 'glsl', value: 'glsl' },
                    { title: 'gnuplot', value: 'gnuplot' },
                    { title: 'go', value: 'go' },
                    { title: 'gql', value: 'gql' },
                    { title: 'graphql', value: 'graphql' },
                    { title: 'groovy', value: 'groovy' },
                    { title: 'gts', value: 'gts' },
                    { title: 'hack', value: 'hack' },
                    { title: 'haml', value: 'haml' },
                    { title: 'handlebars', value: 'handlebars' },
                    { title: 'haskell', value: 'haskell' },
                    { title: 'haxe', value: 'haxe' },
                    { title: 'hbs', value: 'hbs' },
                    { title: 'hcl', value: 'hcl' },
                    { title: 'hjson', value: 'hjson' },
                    { title: 'hlsl', value: 'hlsl' },
                    { title: 'hs', value: 'hs' },
                    { title: 'html', value: 'html' },
                    { title: 'html-derivative', value: 'html-derivative' },
                    { title: 'http', value: 'http' },
                    { title: 'hxml', value: 'hxml' },
                    { title: 'hy', value: 'hy' },
                    { title: 'imba', value: 'imba' },
                    { title: 'ini', value: 'ini' },
                    { title: 'jade', value: 'jade' },
                    { title: 'java', value: 'java' },
                    { title: 'javascript', value: 'javascript' },
                    { title: 'jinja', value: 'jinja' },
                    { title: 'jison', value: 'jison' },
                    { title: 'jl', value: 'jl' },
                    { title: 'js', value: 'js' },
                    { title: 'json', value: 'json' },
                    { title: 'json5', value: 'json5' },
                    { title: 'jsonc', value: 'jsonc' },
                    { title: 'jsonl', value: 'jsonl' },
                    { title: 'jsonnet', value: 'jsonnet' },
                    { title: 'jssm', value: 'jssm' },
                    { title: 'jsx', value: 'jsx' },
                    { title: 'julia', value: 'julia' },
                    { title: 'kotlin', value: 'kotlin' },
                    { title: 'kql', value: 'kql' },
                    { title: 'kt', value: 'kt' },
                    { title: 'kts', value: 'kts' },
                    { title: 'kusto', value: 'kusto' },
                    { title: 'latex', value: 'latex' },
                    { title: 'lean', value: 'lean' },
                    { title: 'lean4', value: 'lean4' },
                    { title: 'less', value: 'less' },
                    { title: 'liquid', value: 'liquid' },
                    { title: 'lisp', value: 'lisp' },
                    { title: 'lit', value: 'lit' },
                    { title: 'llvm', value: 'llvm' },
                    { title: 'log', value: 'log' },
                    { title: 'logo', value: 'logo' },
                    { title: 'lua', value: 'lua' },
                    { title: 'luau', value: 'luau' },
                    { title: 'make', value: 'make' },
                    { title: 'makefile', value: 'makefile' },
                    { title: 'markdown', value: 'markdown' },
                    { title: 'marko', value: 'marko' },
                    { title: 'matlab', value: 'matlab' },
                    { title: 'md', value: 'md' },
                    { title: 'mdc', value: 'mdc' },
                    { title: 'mdx', value: 'mdx' },
                    { title: 'mediawiki', value: 'mediawiki' },
                    { title: 'mermaid', value: 'mermaid' },
                    { title: 'mips', value: 'mips' },
                    { title: 'mipsasm', value: 'mipsasm' },
                    { title: 'mmd', value: 'mmd' },
                    { title: 'mojo', value: 'mojo' },
                    { title: 'move', value: 'move' },
                    { title: 'nar', value: 'nar' },
                    { title: 'narrat', value: 'narrat' },
                    { title: 'nextflow', value: 'nextflow' },
                    { title: 'nf', value: 'nf' },
                    { title: 'nginx', value: 'nginx' },
                    { title: 'nim', value: 'nim' },
                    { title: 'nix', value: 'nix' },
                    { title: 'nu', value: 'nu' },
                    { title: 'nushell', value: 'nushell' },
                    { title: 'objc', value: 'objc' },
                    { title: 'objective-c', value: 'objective-c' },
                    { title: 'objective-cpp', value: 'objective-cpp' },
                    { title: 'ocaml', value: 'ocaml' },
                    { title: 'pascal', value: 'pascal' },
                    { title: 'perl', value: 'perl' },
                    { title: 'perl6', value: 'perl6' },
                    { title: 'php', value: 'php' },
                    { title: 'plsql', value: 'plsql' },
                    { title: 'po', value: 'po' },
                    { title: 'polar', value: 'polar' },
                    { title: 'postcss', value: 'postcss' },
                    { title: 'pot', value: 'pot' },
                    { title: 'potx', value: 'potx' },
                    { title: 'powerquery', value: 'powerquery' },
                    { title: 'powershell', value: 'powershell' },
                    { title: 'prisma', value: 'prisma' },
                    { title: 'prolog', value: 'prolog' },
                    { title: 'properties', value: 'properties' },
                    { title: 'proto', value: 'proto' },
                    { title: 'protobuf', value: 'protobuf' },
                    { title: 'ps', value: 'ps' },
                    { title: 'ps1', value: 'ps1' },
                    { title: 'pug', value: 'pug' },
                    { title: 'puppet', value: 'puppet' },
                    { title: 'purescript', value: 'purescript' },
                    { title: 'py', value: 'py' },
                    { title: 'python', value: 'python' },
                    { title: 'ql', value: 'ql' },
                    { title: 'qml', value: 'qml' },
                    { title: 'qmldir', value: 'qmldir' },
                    { title: 'qss', value: 'qss' },
                    { title: 'r', value: 'r' },
                    { title: 'racket', value: 'racket' },
                    { title: 'raku', value: 'raku' },
                    { title: 'razor', value: 'razor' },
                    { title: 'rb', value: 'rb' },
                    { title: 'reg', value: 'reg' },
                    { title: 'regex', value: 'regex' },
                    { title: 'regexp', value: 'regexp' },
                    { title: 'rel', value: 'rel' },
                    { title: 'riscv', value: 'riscv' },
                    { title: 'rs', value: 'rs' },
                    { title: 'rst', value: 'rst' },
                    { title: 'ruby', value: 'ruby' },
                    { title: 'rust', value: 'rust' },
                    { title: 'sas', value: 'sas' },
                    { title: 'sass', value: 'sass' },
                    { title: 'scala', value: 'scala' },
                    { title: 'scheme', value: 'scheme' },
                    { title: 'scss', value: 'scss' },
                    { title: 'sdbl', value: 'sdbl' },
                    { title: 'sh', value: 'sh' },
                    { title: 'shader', value: 'shader' },
                    { title: 'shaderlab', value: 'shaderlab' },
                    { title: 'shell', value: 'shell' },
                    { title: 'shellscript', value: 'shellscript' },
                    { title: 'shellsession', value: 'shellsession' },
                    { title: 'smalltalk', value: 'smalltalk' },
                    { title: 'solidity', value: 'solidity' },
                    { title: 'soy', value: 'soy' },
                    { title: 'sparql', value: 'sparql' },
                    { title: 'spl', value: 'spl' },
                    { title: 'splunk', value: 'splunk' },
                    { title: 'sql', value: 'sql' },
                    { title: 'ssh-config', value: 'ssh-config' },
                    { title: 'stata', value: 'stata' },
                    { title: 'styl', value: 'styl' },
                    { title: 'stylus', value: 'stylus' },
                    { title: 'svelte', value: 'svelte' },
                    { title: 'swift', value: 'swift' },
                    { title: 'system-verilog', value: 'system-verilog' },
                    { title: 'systemd', value: 'systemd' },
                    { title: 'talon', value: 'talon' },
                    { title: 'talonscript', value: 'talonscript' },
                    { title: 'tasl', value: 'tasl' },
                    { title: 'tcl', value: 'tcl' },
                    { title: 'templ', value: 'templ' },
                    { title: 'terraform', value: 'terraform' },
                    { title: 'tex', value: 'tex' },
                    { title: 'tf', value: 'tf' },
                    { title: 'tfvars', value: 'tfvars' },
                    { title: 'toml', value: 'toml' },
                    { title: 'ts', value: 'ts' },
                    { title: 'ts-tags', value: 'ts-tags' },
                    { title: 'tsp', value: 'tsp' },
                    { title: 'tsv', value: 'tsv' },
                    { title: 'tsx', value: 'tsx' },
                    { title: 'turtle', value: 'turtle' },
                    { title: 'twig', value: 'twig' },
                    { title: 'typ', value: 'typ' },
                    { title: 'typescript', value: 'typescript' },
                    { title: 'typespec', value: 'typespec' },
                    { title: 'typst', value: 'typst' },
                    { title: 'v', value: 'v' },
                    { title: 'vala', value: 'vala' },
                    { title: 'vb', value: 'vb' },
                    { title: 'verilog', value: 'verilog' },
                    { title: 'vhdl', value: 'vhdl' },
                    { title: 'vim', value: 'vim' },
                    { title: 'viml', value: 'viml' },
                    { title: 'vimscript', value: 'vimscript' },
                    { title: 'vue', value: 'vue' },
                    { title: 'vue-html', value: 'vue-html' },
                    { title: 'vy', value: 'vy' },
                    { title: 'vyper', value: 'vyper' },
                    { title: 'wasm', value: 'wasm' },
                    { title: 'wenyan', value: 'wenyan' },
                    { title: 'wgsl', value: 'wgsl' },
                    { title: 'wiki', value: 'wiki' },
                    { title: 'wikitext', value: 'wikitext' },
                    { title: 'wit', value: 'wit' },
                    { title: 'wl', value: 'wl' },
                    { title: 'wolfram', value: 'wolfram' },
                    { title: 'xml', value: 'xml' },
                    { title: 'xsl', value: 'xsl' },
                    { title: 'yaml', value: 'yaml' },
                    { title: 'yml', value: 'yml' },
                    { title: 'zenscript', value: 'zenscript' },
                    { title: 'zig', value: 'zig' },
                    { title: 'zsh', value: 'zsh' },
                ],
            },
            validation: rule => rule.required(),
        }),
        defineField({
            name: 'code',
            type: 'text',
            title: 'Code',
            description: 'Code Snippet',
            initialValue: '',
            validation: rule => rule.required(),
        }),
    ],
    preview: {
        select: {
            title: 'name',
            type: 'type',
        },
        prepare: ({ title, type }) => ({ title: `Code (${type || 'n/a'})`, subtitle: title }),
    },
})
